[package]
name = "rl_ref1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rl_math_lib = { git = "https://github.com/OfflineBot/rl_math_lib" }